build: Fix compilation with GCC 10
Scanning dependencies of target RD
make[2]: Leaving directory '/root/dg/build'
make[2]: Entering directory '/root/dg/build'
[  1%] Building CXX object lib/CMakeFiles/RD.dir/analysis/ReachingDefinitions/BasicRDMap.cpp.o
In file included from /usr/include/c++/10/utility:70,
                 from /usr/include/c++/10/algorithm:60,
                 from /root/dg/lib/analysis/ReachingDefinitions/BasicRDMap.cpp:1:
/usr/include/c++/10/bits/stl_pair.h: In instantiation of ‘struct std::pair<const std::__cxx11::basic_string<char>, dg::analysis::AllocationFunction>’:
/root/dg/include/dg/analysis/AnalysisOptions.h:38:5:   required from here
/usr/include/c++/10/bits/stl_pair.h:216:11: error: ‘std::pair<_T1, _T2>::first’ has incomplete type
  216 |       _T1 first;                 ///< The first member
      |           ^~~~~
...

Scanning dependencies of target PTA
make[2]: Leaving directory '/root/dg/build'
make[2]: Entering directory '/root/dg/build'
[  5%] Building CXX object lib/CMakeFiles/PTA.dir/analysis/PointsTo/Pointer.cpp.o
[  7%] Building CXX object lib/CMakeFiles/PTA.dir/analysis/PointsTo/PointerAnalysis.cpp.o
In file included from /root/dg/include/dg/analysis/PointsTo/PointsToSet.h:6,
                 from /root/dg/lib/analysis/PointsTo/PointerAnalysis.cpp:2:
/root/dg/include/dg/analysis/PointsTo/PointsToSets/SeparateOffsetsPointsToSet.h: In member function ‘bool dg::analysis::pta::SeparateOffsetsPointsToSet::remove(const dg::analysis::pta::Pointer&)’:
/root/dg/include/dg/analysis/PointsTo/PointsToSets/SeparateOffsetsPointsToSet.h:58:9: error: ‘abort’ was not declared in this scope
   58 |         abort();
      |         ^~~~~
/root/dg/include/dg/analysis/PointsTo/PointsToSets/SeparateOffsetsPointsToSet.h:59:5: warning: no return statement in function returning non-void [-Wreturn-type]
   59 |     }
      |     ^
...

Scanning dependencies of target dgThreadRegions
make[2]: Leaving directory '/root/dg/build'
make[2]: Entering directory '/root/dg/build'
[ 30%] Building CXX object lib/CMakeFiles/dgThreadRegions.dir/llvm/analysis/ThreadRegions/sources/Nodes/Node.cpp.o
...
[ 48%] Building CXX object lib/CMakeFiles/dgThreadRegions.dir/llvm/analysis/ThreadRegions/sources/Graphs/GraphBuilder.cpp.o
In file included from /root/dg/lib/llvm/analysis/ThreadRegions/sources/Graphs/GraphBuilder.cpp:1:
/root/dg/lib/llvm/analysis/ThreadRegions/include/Graphs/GraphBuilder.h:82:21: error: ‘std::ostream’ has not been declared
   82 |     void print(std::ostream & ostream) const;
      |                     ^~~~~~~
/root/dg/lib/llvm/analysis/ThreadRegions/include/Graphs/GraphBuilder.h:84:26: error: ‘std::ostream’ has not been declared
   84 |     void printNodes(std::ostream & ostream) const;
      |                          ^~~~~~~
/root/dg/lib/llvm/analysis/ThreadRegions/include/Graphs/GraphBuilder.h:86:26: error: ‘std::ostream’ has not been declared
   86 |     void printEdges(std::ostream & ostream) const;
      |                          ^~~~~~~