llvm13: llvm::VectorType::getNumElements has been removed
... and getElementCount should be used instead.

Fixes:
error: no member named 'getNumElements' in 'llvm::VectorType'