CMake: fix linking of shared libs
I see:
llvm/analysis/PointsTo/PointerSubgraph.cpp.o: In function `dg::analysis::pta::getMemAllocationFunc(llvm::Function const*) [clone .part.6]':
/home/abuild/rpmbuild/BUILD/dg-0.0+20161130/src/llvm/analysis/PointsTo/PointerSubgraph.cpp:112: undefined reference to `llvm::Value::getName() const'

LLVMpta needs LLVMCore and LLVMSupport, so handle it properly.

Guard the addition by BUILD_SHARED_LIBS, as it causes troubles for
static libs (doubled symbols etc.)

Also mark them PUBLIC appropriatelly -- we use the libs both in exported
headers and our sources in libraries. Mark tools as PRIVATE users.

Signed-off-by: Jiri Slaby <slaby@fi.muni.cz>